CREATE TABLE category
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (id)
);

CREATE TABLE brands
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    logo_url    VARCHAR(255),
    CONSTRAINT pk_brands PRIMARY KEY (id)
);

CREATE TABLE inventory_products
(
    id          UUID NOT NULL,
    name        VARCHAR(50) NOT NULL,
    description VARCHAR(255) NOT NULL,
    price       NUMERIC(19, 2) NOT NULL,
    stock       INTEGER NOT NULL,
    active      BOOLEAN NOT NULL,
    image       VARCHAR(255) NOT NULL,
    rating      DOUBLE PRECISION NOT NULL,
    brand_id    BIGINT NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_inventory_products PRIMARY KEY (id)
);

CREATE TABLE product_category
(
    category_id BIGINT NOT NULL,
    product_id  UUID   NOT NULL,
    CONSTRAINT pk_product_category PRIMARY KEY (category_id, product_id)
);

CREATE TABLE roles
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE user_auths
(
    id                      UUID         NOT NULL,
    email                   VARCHAR(255) NOT NULL,
    password                VARCHAR(255) NOT NULL,
    enabled                 BOOLEAN      NOT NULL,
    account_non_expired     BOOLEAN      NOT NULL,
    account_non_locked      BOOLEAN      NOT NULL,
    credentials_non_expired BOOLEAN      NOT NULL,
    created_date            TIMESTAMP WITHOUT TIME ZONE,
    updated_date            TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_user_auths PRIMARY KEY (id)
);

CREATE TABLE user_profiles
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name   VARCHAR(100) NOT NULL,
    last_name    VARCHAR(100) NOT NULL,
    user_auth_id UUID NOT NULL,
    CONSTRAINT pk_user_profiles PRIMARY KEY (id)
);

CREATE TABLE user_roles
(
    role_id BIGINT NOT NULL,
    user_id UUID   NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (role_id, user_id)
);

ALTER TABLE roles
    ADD CONSTRAINT uc_roles_role UNIQUE (role);

ALTER TABLE category
    ADD CONSTRAINT uc_category_name UNIQUE (name);

ALTER TABLE brands
    ADD CONSTRAINT uc_brands_name UNIQUE (name);

ALTER TABLE user_auths
    ADD CONSTRAINT uc_user_auths_email UNIQUE (email);

ALTER TABLE user_profiles
    ADD CONSTRAINT uc_user_profiles_user_auth_id UNIQUE (user_auth_id);

ALTER TABLE user_profiles
    ADD CONSTRAINT FK_USER_PROFILES_ON_USERAUTH FOREIGN KEY (user_auth_id) REFERENCES user_auths (id);

ALTER TABLE product_category
    ADD CONSTRAINT fk_procat_on_category FOREIGN KEY (category_id) REFERENCES category (id);

ALTER TABLE product_category
    ADD CONSTRAINT fk_procat_on_product FOREIGN KEY (product_id) REFERENCES inventory_products (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_role FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_user_auth FOREIGN KEY (user_id) REFERENCES user_auths (id);

ALTER TABLE inventory_products
    ADD CONSTRAINT fk_inventory_products_on_brand FOREIGN KEY (brand_id) REFERENCES brands (id);
